run_name: "Initial Run Test"

indir: "/work/crosslab/hsommer/syntax_testing"
index_dir: "/work/crosslab/hsommer/TRAPS/indexes/bwamem2_indexes/NC_009942-1"
outdir: "/work/crosslab/hsommer/run4"
containers: "/work/crosslab/hsommer/TRAPS/containers"
workDir: outdir
references: "two_refs.csv"

cpus: 12

qc:
  min_depth: 10

single_end: true
sequencing_tech: "illumina"

alignment:
  tool: "bwa-mem2"