run_name: "my_run"

indir: "/work/crosslab/hsommer/syntax2"
outdir: "/work/crosslab/hsommer/run10"
workDir: outdir
references: "/work/crosslab/hsommer/TRAPS/workflow/two_refs.csv"

cpus: 12

qc:
  min_breadth_percent: 90
  min_depth: 5

single_end: true
sequencing_tech: "illumina"

alignment:
  tool: "bwa-mem2"